### ISSUE TITLE
имена переменных

### ISSUE THREAD

**Issue by dzhivushko** [artemama/JD1#11]
https://github.com/artemama/JD1/blob/b5c34db7afa153ed7fe9b28a84398e5ae51de9cd/src/com/itacademy/task21/TimeStringSumm.java#L13
что такое timeSpent? это затраченное время. но затраченное время - это начальное минус конечное. в итоге у тебя  timeSpent - это то, что на самом деле обозначает точку во времени, а не затраченное время. если в таком стиле путать имена переменных с их значением, то получится все плохо. это не мелочи - это важно

**Comment by artemama** [comment]
понял
