### ISSUE TITLE
непонятное решение

### ISSUE THREAD

**Issue by dzhivushko** [artemama/JD1#13]
https://github.com/artemama/JD1/blob/b5c34db7afa153ed7fe9b28a84398e5ae51de9cd/src/com/itacademy/task21/TimeStringSumm.java#L9-L21
я тут вообще не понял если честно. почему один цикл до 20, а другой до 20 000. и зачем там где распечатывается строка стоит умножение миллисекунд на 1000

**Comment by artemama** [comment]
т.к. если второй цикл делать до 20, то результат - 0, т.е. слишком малое число

**Comment by dzhivushko** [comment]
вместо миллисекунд надо померять наносекунды. есть соответствующий метод в System.

**Comment by artemama** [comment]
теперь все сработало
вопрос - если в первой части i ставлю <21 и далее, то выскакивает ошибка нехватка памяти
http://ipic.su/img/img7/fs/kiss_39kb.1514205221.jpg
