### ISSUE TITLE
локальные переменные пишутся с маленькой буквы

### ISSUE THREAD

**Issue by dzhivushko** [artemama/JD1#15]
https://github.com/artemama/JD1/blob/b5c34db7afa153ed7fe9b28a84398e5ae51de9cd/src/com/itacademy/task23/Bankomat.java#L6

**Comment by artemama** [comment]
понял
в моем случае cM1 / cm1 как правильнее?

**Comment by artemama** [comment]
понял
в моем случае cM1 / cm1 как правильнее?

**Comment by dzhivushko** [comment]
это уже сам решай. главное не начинай с большой
