### ISSUE TITLE
это надо сделать через Iterator

### ISSUE THREAD

**Issue by dzhivushko** [artemama/JD1#19]
https://github.com/artemama/JD1/blob/b5c34db7afa153ed7fe9b28a84398e5ae51de9cd/src/com/itacademy/task26/MarksArrList.java#L15-L24

**Comment by dzhivushko** [comment]
я оценку не снижал. так тоже работает. но тут есть индекс i. такой вариант считается небезопасным. потому переделай на итератор чтобы увидеть разницу и уметь им пользоваться

**Comment by artemama** [comment]
Сделал
