### ISSUE TITLE
халтура?

### ISSUE THREAD

**Issue by dzhivushko** [artemama/JD1#3]
https://github.com/artemama/JD1/blob/9b210f4844083bc5f8509603c953ba6a4cfa1d66/src/com/intexsoft/task04/Rectangle.java#L5-L15

здесь какие вычисления есть (и вроде по теме), но я не вижу выполнения самого условия - ответа попадет прямоугольник в круг полностью или нет

**Comment by artemama** [comment]
Не до конца вник в вопрос задачи
исправил
