### ISSUE TITLE
повторение кода

### ISSUE THREAD

**Issue by dzhivushko** [artemama/JD1#4]
https://github.com/artemama/JD1/blob/9b210f4844083bc5f8509603c953ba6a4cfa1d66/src/com/intexsoft/task06/Data.java#L18

эта строчка повторяется множество раз. ее как минимум надо вынести в метод (да, даже 1 строку  -в отдельный метод приватный). но мне кажется что эту строку и вовсе можно просто опустить в самый низ после всех if/else и вывести результат в одном месте

**Comment by artemama** [comment]
согласен, исправил
