### ISSUE TITLE
слишком много уровней вложенности

### ISSUE THREAD

**Issue by dzhivushko** [artemama/JD1#5]
https://github.com/artemama/JD1/blob/9b210f4844083bc5f8509603c953ba6a4cfa1d66/src/com/intexsoft/task07/Homes.java#L12-L32

должно быть не больше 2х вложенных блоков. лучше и вовсе не больше одного блока внутри метода.
упростить можно выносом отдельных условных (if/else) блоков или циклов в отдельные приватные методы

**Comment by artemama** [comment]
согласен, исправил, убирал else везде, кроме последнего элемента
логика не поменялась
