### ISSUE TITLE
неверное расположение инициализации переменной

### ISSUE THREAD

**Issue by dzhivushko** [artemama/JD1#6]
https://github.com/artemama/JD1/blob/9b210f4844083bc5f8509603c953ba6a4cfa1d66/src/com/intexsoft/task09/MaxNum.java#L10-L21
переменная cicle. зачем она существует снаружи от блока for( ) { }
ведь используется она только внутри него.
переменные объявляются как можно ближе к месту первого использования. ни в коем случае нельзя объявлять переменные заранее с более широкой областью видимости, чем это надо ей на самом деле

**Comment by artemama** [comment]
исправил
