### ISSUE TITLE
упростить метод

### ISSUE THREAD

**Issue by dzhivushko** [artemama/JD1#7]
https://github.com/artemama/JD1/blob/a5649854ff04215cd4c846522d49ed91c473d794/src/com/itacademy/task13/SimpleNumberBrake.java#L5-L26

в твоем пример там где else { if(){} можно убрать одну пару скобок и ничего не изменится. но уберется 1 ступенька вложенности

public static void main(String[] args) {

		int number = 167;
		int temp = 1;
		for (int i = 2; i < number + 1; i++) {
			temp = number % i;
			if (temp == 0 && i != number) {
				System.out.println(number + " - a composite number");
				break;

			} else if (temp == 0 && i == number) {
				System.out.println(number + " - Simple number");
			}

		}
	}

**Comment by artemama** [comment]
+
