### ISSUE TITLE
не усложняй имена переменных

### ISSUE THREAD

**Issue by dzhivushko** [artemama/JD1#9]
https://github.com/artemama/JD1/blob/a5649854ff04215cd4c846522d49ed91c473d794/src/com/itacademy/task15/SumMinMaxMarks.java#L39

имена переменных, методов, классов должны говорить о своем содержимом. но вот это пример когда можно перебарщить.
я бы назвал прсто minIndex/maxIndex.  имя переменной не должно быть "немым". но и сильно много писать тоже не надо

**Comment by artemama** [comment]
ok
